### ISSUE TITLE
Mentioned

### ISSUE THREAD

**Issue by bbaassssiiee** [eugene-krivosheyev/ansible-artifactory-role#2]
Hi,

I used your code in a PR for the vendor, I hop that's alright with you.
- https://github.com/jfrog/JFrog-Cloud-Installers/pull/335

You might want to join the fun improving the JFrog collection? It's #Hacktoberfest!
- https://github.com/jfrog/JFrog-Cloud-Installers/issues/290

**Comment by eugene-krivosheyev** [comment]
Hi @bbaassssiiee,
I'm glad that my work is valuable for community. Feel free to use any code 😀
